@startuml
   (*) -->[CarNetWorks启动] "等待网络连接"
    --> [网络连接成功] "创建长连接createClient"
    -->"开始发送心跳10分钟一次"
    -->[在线](*)

  (*) -->[收到长连接断开通知] "启动重连接线程ReConnectThread"
      if "重连10次" then
         -->[连接成功] "开始发送心跳10分钟一次"
      else
         -->[重连失败] "离线"
      endif
   (*) -->[ACC ON ]  "检查在线离线状态"
       if "判断是否在线" then
          --> [在线](*)
       else
          --> [离线] "创建长连接createClient重连10次"
          --> "重新走重连流程"
       endif
    (*) --> [网络恢复] "检查在线离线状态"

@enduml
